tamper.*:
  type: mapping
  label: 'Tamper plugin'

tamper.convert_case:
  mapping:
    operation:
      type: string
      label: 'How to convert case'

tamper.default_value:
  mapping:
    default_value:
      type: string
      label: 'Value'
    only_if_empty:
      type: boolean
      label: 'Only if empty'

tamper.explode:
  mapping:
    separator:
      type: string
      label: 'String separator'
    limit:
      type: integer
      label: 'Limit'

tamper.find_replace:
  mapping:
    find:
      type: string
      label: 'Text to find'
    replace:
      type: string
      label: 'Text to replace'
    case_sensitive:
      type: boolean
      label: 'Case sensitive'
    word_boundaries:
      type: boolean
      label: 'Respect word boundaries'
    whole:
      type: boolean
      label: 'Match whole word/phrase'

tamper.find_replace_regex:
  mapping:
    find:
      type: string
      label: 'REGEX to find'
    replace:
      type: string
      label: 'Replacement pattern'
    limit:
      type: integer
      label: 'Limit number of replacements'

tamper.hash:
  mapping:
    override:
      type: boolean
      label: 'Override set value'

tamper.implode:
  mapping:
    glue:
      type: string
      label: 'String glue'

tamper.required:
  mapping:
    invert:
      type: boolean
      label: 'Invert filter'

tamper.str_pad:
  mapping:
    pad_length:
      type: integer
      label: 'Pad length'
    pad_string:
      type: string
      label: 'Pad string'
    pad_type:
      type: string
      label: 'Pad type'

tamper.strip_tags:
  mapping:
    allowed_tags:
      type: string
      label: 'Allowed tags'

tamper.trim:
  mapping:
    character:
      type: string
      label: 'Characters to trim'
    side:
      type: string
      label: 'Side'

