module:
  address: 0
  address_map_link: 0
  advagg: 0
  advagg_cdn: 0
  advagg_css_minify: 0
  advagg_js_minify: 0
  advagg_mod: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  coffee: 0
  colorbox: 0
  config: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  feeds: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  imageapi_optimize: 0
  imageapi_optimize_binaries: 0
  improved_multi_select: 0
  instagram_without_api: 0
  kint: 0
  leaflet: 0
  leaflet_markercluster: 0
  leaflet_views: 0
  link: 0
  link_target: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  redirect_domain: 0
  responsive_image: 0
  search: 0
  select_or_other: 0
  shortcut: 0
  simple_sitemap: 0
  sy_mapping: 0
  system: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  sy_bootstrap: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
